server:
  port: 8444
spring.profiles.active: eureka-ssl
logging:
  file: /java/MHC_LOGS/pp-ui/ppui.log
info:
  component: Patient Portal UI
eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}
#    hostname: localhost
    secure-port-enabled: false
    non-secure-port-enabled: true
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
spring.profiles: ssl
server:
  port: 8444
  ssl:
    key-store: /ssl_keystore.keystore
    key-store-password: changeit
eureka:
  instance:
    secure-port: ${server.port}
    secure-port-enabled: true
    non-secure-port-enabled: false
---
spring.profiles: standalone-ssl
spring:
  profiles:
    include: ssl
server:
  context-path: /pp-ui
---
spring.profiles: eureka-ssl
eureka:
  client:
    service-url:
      defaultZone: https://localhost:8761/eureka/
---
spring.profiles: docker
eureka:
  client:
    service-url:
      defaultZone: https://discovery-server.c2s.com:8761/eureka/
  instance:
    prefer-ip-address: true