# application.yml template
server:
  contextPath: /pp-ui
  port: 8444
  ssl:
    key-store: /java/keystore/ssl_keystore.keystore
    key-store-password: changeit
logging:
  file: /java/MHC_LOGS/pp-ui/ppui.log